# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PropagationCalculator.ui'
#
# Created: Fri Nov 28 16:49:40 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PropagationCalculator(object):
    def setupUi(self, PropagationCalculator):
        PropagationCalculator.setObjectName(_fromUtf8("PropagationCalculator"))
        PropagationCalculator.resize(1351, 871)
        self.centralwidget = QtGui.QWidget(PropagationCalculator)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setMaximumSize(QtCore.QSize(80, 25))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.auto_analysis = QtGui.QPushButton(self.centralwidget)
        self.auto_analysis.setObjectName(_fromUtf8("auto_analysis"))
        self.gridLayout.addWidget(self.auto_analysis, 2, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(1041, 671))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.East)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabWidgetPage1 = QtGui.QWidget()
        self.tabWidgetPage1.setObjectName(_fromUtf8("tabWidgetPage1"))
        self.tabWidget.addTab(self.tabWidgetPage1, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 4, 9, 1)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout.addWidget(self.progressBar, 1, 0, 1, 2)
        PropagationCalculator.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(PropagationCalculator)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        PropagationCalculator.setStatusBar(self.statusbar)
        self.menuBar = QtGui.QMenuBar(PropagationCalculator)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1351, 27))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menuBar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuView = QtGui.QMenu(self.menuBar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuRun = QtGui.QMenu(self.menuBar)
        self.menuRun.setObjectName(_fromUtf8("menuRun"))
        self.menuAutomatic_Analysis = QtGui.QMenu(self.menuBar)
        self.menuAutomatic_Analysis.setObjectName(_fromUtf8("menuAutomatic_Analysis"))
        PropagationCalculator.setMenuBar(self.menuBar)
        self.actionAxon_binary_file = QtGui.QAction(PropagationCalculator)
        self.actionAxon_binary_file.setObjectName(_fromUtf8("actionAxon_binary_file"))
        self.actionOpen_Data = QtGui.QAction(PropagationCalculator)
        self.actionOpen_Data.setObjectName(_fromUtf8("actionOpen_Data"))
        self.actionSave_Data = QtGui.QAction(PropagationCalculator)
        self.actionSave_Data.setObjectName(_fromUtf8("actionSave_Data"))
        self.actionExport_Graphic = QtGui.QAction(PropagationCalculator)
        self.actionExport_Graphic.setObjectName(_fromUtf8("actionExport_Graphic"))
        self.actionQuit = QtGui.QAction(PropagationCalculator)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionShow_Axes = QtGui.QAction(PropagationCalculator)
        self.actionShow_Axes.setCheckable(True)
        self.actionShow_Axes.setChecked(True)
        self.actionShow_Axes.setObjectName(_fromUtf8("actionShow_Axes"))
        self.actionShow_Data = QtGui.QAction(PropagationCalculator)
        self.actionShow_Data.setObjectName(_fromUtf8("actionShow_Data"))
        self.actionAbsolute_Value = QtGui.QAction(PropagationCalculator)
        self.actionAbsolute_Value.setObjectName(_fromUtf8("actionAbsolute_Value"))
        self.actionAlter_Markers = QtGui.QAction(PropagationCalculator)
        self.actionAlter_Markers.setCheckable(True)
        self.actionAlter_Markers.setEnabled(False)
        self.actionAlter_Markers.setObjectName(_fromUtf8("actionAlter_Markers"))
        self.actionAbsolute_Value_2 = QtGui.QAction(PropagationCalculator)
        self.actionAbsolute_Value_2.setCheckable(True)
        self.actionAbsolute_Value_2.setChecked(False)
        self.actionAbsolute_Value_2.setObjectName(_fromUtf8("actionAbsolute_Value_2"))
        self.actionFilter = QtGui.QAction(PropagationCalculator)
        self.actionFilter.setCheckable(True)
        self.actionFilter.setChecked(False)
        self.actionFilter.setObjectName(_fromUtf8("actionFilter"))
        self.actionFilter_Config = QtGui.QAction(PropagationCalculator)
        self.actionFilter_Config.setObjectName(_fromUtf8("actionFilter_Config"))
        self.actionAnalyse_waveform_currently_loaded = QtGui.QAction(PropagationCalculator)
        self.actionAnalyse_waveform_currently_loaded.setObjectName(_fromUtf8("actionAnalyse_waveform_currently_loaded"))
        self.actionAnalyse_multiple_additional_files = QtGui.QAction(PropagationCalculator)
        self.actionAnalyse_multiple_additional_files.setObjectName(_fromUtf8("actionAnalyse_multiple_additional_files"))
        self.actionSet_threshold = QtGui.QAction(PropagationCalculator)
        self.actionSet_threshold.setObjectName(_fromUtf8("actionSet_threshold"))
        self.actionSet_width = QtGui.QAction(PropagationCalculator)
        self.actionSet_width.setObjectName(_fromUtf8("actionSet_width"))
        self.menuFile.addAction(self.actionOpen_Data)
        self.menuFile.addAction(self.actionSave_Data)
        self.menuFile.addAction(self.actionExport_Graphic)
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionAlter_Markers)
        self.menuView.addAction(self.actionShow_Axes)
        self.menuView.addAction(self.actionShow_Data)
        self.menuRun.addAction(self.actionAbsolute_Value_2)
        self.menuRun.addAction(self.actionFilter)
        self.menuRun.addAction(self.actionFilter_Config)
        self.menuAutomatic_Analysis.addAction(self.actionAnalyse_waveform_currently_loaded)
        self.menuAutomatic_Analysis.addAction(self.actionAnalyse_multiple_additional_files)
        self.menuAutomatic_Analysis.addAction(self.actionSet_threshold)
        self.menuAutomatic_Analysis.addAction(self.actionSet_width)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuRun.menuAction())
        self.menuBar.addAction(self.menuAutomatic_Analysis.menuAction())

        self.retranslateUi(PropagationCalculator)
        QtCore.QMetaObject.connectSlotsByName(PropagationCalculator)

    def retranslateUi(self, PropagationCalculator):
        PropagationCalculator.setWindowTitle(_translate("PropagationCalculator", "Propagation Calculator", None))
        self.pushButton.setText(_translate("PropagationCalculator", "Load File", None))
        self.auto_analysis.setText(_translate("PropagationCalculator", "Auto Analysis", None))
        self.menuFile.setTitle(_translate("PropagationCalculator", "File", None))
        self.menuEdit.setTitle(_translate("PropagationCalculator", "Edit", None))
        self.menuView.setTitle(_translate("PropagationCalculator", "View", None))
        self.menuRun.setTitle(_translate("PropagationCalculator", "Variables", None))
        self.menuAutomatic_Analysis.setTitle(_translate("PropagationCalculator", "Automatic Analysis", None))
        self.actionAxon_binary_file.setText(_translate("PropagationCalculator", "axon binary file", None))
        self.actionOpen_Data.setText(_translate("PropagationCalculator", "Open Data", None))
        self.actionSave_Data.setText(_translate("PropagationCalculator", "Save Data", None))
        self.actionExport_Graphic.setText(_translate("PropagationCalculator", "Export Graphic", None))
        self.actionQuit.setText(_translate("PropagationCalculator", "Quit", None))
        self.actionShow_Axes.setText(_translate("PropagationCalculator", "Show Axes", None))
        self.actionShow_Data.setText(_translate("PropagationCalculator", "Show Data", None))
        self.actionAbsolute_Value.setText(_translate("PropagationCalculator", "Absolute Value", None))
        self.actionAlter_Markers.setText(_translate("PropagationCalculator", "Alter Markers", None))
        self.actionAbsolute_Value_2.setText(_translate("PropagationCalculator", "Absolute Value", None))
        self.actionFilter.setText(_translate("PropagationCalculator", "Filter", None))
        self.actionFilter_Config.setText(_translate("PropagationCalculator", "Filter Config", None))
        self.actionAnalyse_waveform_currently_loaded.setText(_translate("PropagationCalculator", "Analyse file currently loaded", None))
        self.actionAnalyse_multiple_additional_files.setText(_translate("PropagationCalculator", "Analyse multiple additional files", None))
        self.actionSet_threshold.setText(_translate("PropagationCalculator", "Set threshold", None))
        self.actionSet_width.setText(_translate("PropagationCalculator", "Set window", None))

